# Generated by Django 4.2 on 2023-04-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="type",
            field=models.CharField(
                choices=[
                    ("nature", "nature"),
                    ("animal", "animal"),
                    ("other", "other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
